name: Deploy Python Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'multi_tool_agent/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '!README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/loan-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy loan-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/loan-backend \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
